### ISSUE TITLE
Missing SP Metadata Descriptor

### ISSUE THREAD

**Issue by pibragh** [nicolabeghin/keycloak-spid-provider-configuration-client#4]
In case of private SP, there is a set of metadata descriptor elements that are not managed by the current implementation, so the SPID Validator raises some errors.

I added such missing attributes to my working copy, how can I share with you my job ? Can you create a branch for it where I can push my changes ?

**Comment by nicolabeghin** [comment]
@pibragh sure just raise a PR!
